name: Main workflow

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Set up virtual environment
        run: |
          python -m venv venv
          source /home/vscode/venv/bin/activate
          cd /workspaces/travel-weather/

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run tests
        run: make test